version: "3.9"

networks:
  mk-network:
    driver: "bridge"

services:
  mk-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: makeorder
    ports:
      - "5435:5432"
    networks:
      - mk-network

  mk-api:
    build: .
    image: make-order-api
    command: ["/wait-for-it.sh", "-t", "10", "mk-database:5435", "--", "java", "-jar", "mk-api.jar"]
    environment:
      DB_URL:
      DB_USER:
      DB_PASSWORD:

      KEY:

      EMAIL:
      PASSWORD:
    networks:
      - mk-network
    depends_on:
      - mk-database

  mk-proxy:
    build: ./nginx
    image: mk-proxy
    ports:
      - "80:80"
    networks:
      - mk-network
    depends_on:
      - mk-api