spring.datasource.url={URL}
spring.datasource.username={USER}
spring.datasource.password={PASSWORD}
spring.jooq.sql-dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop

api.security.token.secret={JWT_SECRET:my-secret-key}