spring.datasource.url=jdbc:postgresql://server-db.postgres.database.azure.com:5432/makeorder
spring.datasource.username=project
spring.datasource.password=#Ubnt2020
spring.jooq.sql-dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret={JWT_SECRET:my-secret-key}