#Configurações do H2
spring.datasource.url=jdbc:postgresql://localhost:5432/makeorder
spring.datasource.username=postgres
spring.datasource.password=1234567
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=true