spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}
spring.jooq.sql-dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=create-drop

api.security.token.secret={JWT_SECRET:my-secret-key}

spring.flyway.user=${USER}
spring.flyway.password=${PASSWORD}
spring.flyway.locations=classpath:db/migration