#Configurações do perfil
spring.profiles.active=test

#Configurações do flyway
spring.flyway.user=postgres
spring.flyway.password=1234567
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs.html
springdoc.swagger-ui.operationsSorter=method